version: '3.8'
services:
    redis:
        image: redis:latest
        restart: always
        ports:
            - 6379:6379
        environment:
            REDIS_PASSWORD: ${REDIS_PASSWORD}
        command: redis-server --save 20 10 --loglevel warning --requirepass $REDIS_PASSWORD
    api:
        build: ./test-backend/
        depends_on:
            - redis
        ports:
            - 3000:3000
        environment:
            REDIS_HOST: redis
            REDIS_PORT: 6379
            REDIS_PASSWORD: ${REDIS_PASSWORD}
        command: npm run test
